In [18]:
import sqlite3
import pandas as pd

In [19]:
conn = sqlite3.connect('revelleit.db')

In [20]:
top_5 = pd.read_sql_query("""
    SELECT Marque, Modele, Score_Final, GWP, ADPe, WU, ADPf, TPE, WEEE
    FROM impacts_calcules
    ORDER BY Score_Final DESC
    LIMIT 5
""", conn)

In [21]:
print("Top 5 des équipements avec le meilleur score")
top_5

Top 5 des équipements avec le meilleur score

,Marque,Modele,Score_Final,GWP,ADPe,WU,ADPf,TPE,WEEE
0,HP,ProDesk 600 G7,4.3,314.72,0.009056,8.388,2225.2,3492.4,8.3428
1,HP,ProDesk 600 G7,4.3,314.72,0.009056,8.388,2225.2,3492.4,8.3428
2,HP,Z2 Mini G5,4.2,329.64,0.011712,9.276,2600.4,3400.8,8.4356
3,HP,Z2 Mini G5,4.2,329.64,0.011712,9.276,2600.4,3400.8,8.4356
4,Bull,Evoquer Basic,4.0,338.52,0.009152,8.508,2293.2,3856.0,8.3588

In [27]:
# Tableau de tous les desktops classés par score
all_desktops = pd.read_sql_query("""
    SELECT Marque, Modele, Departement, Score_Final, GWP, ADPe, WU, ADPf, TPE, WEEE
    FROM impacts_calcules
    ORDER BY Score_Final DESC
""", conn)
print("Tous les équipements classés par score :")
all_desktops

Tous les équipements classés par score :

,Marque,Modele,Departement,Score_Final,GWP,ADPe,WU,ADPf,TPE,WEEE
0,HP,ProDesk 600 G7,Communication / Marketing,4.3,314.72,0.009056,8.388,2225.2,3492.4,8.3428
1,HP,ProDesk 600 G7,Communication / Marketing,4.3,314.72,0.009056,8.388,2225.2,3492.4,8.3428
2,HP,ProDesk 600 G7,Communication / Marketing,4.3,314.72,0.009056,8.388,2225.2,3492.4,8.3428
3,HP,Z2 Mini G5,Communication / Marketing,4.2,329.64,0.011712,9.276,2600.4,3400.8,8.4356
4,HP,Z2 Mini G5,Communication / Marketing,4.2,329.64,0.011712,9.276,2600.4,3400.8,8.4356
...,...,...,...,...,...,...,...,...,...,...
70,Fujitsu,Celcius M740,My_Global_Services,1.3,902.60,0.030968,17.460,6444.0,8450.8,9.7280
71,Dell,Precision 3650,Communication / Marketing,1.3,750.80,0.021884,16.280,5322.0,7004.4,9.4140
72,Fujitsu,Celcius M740,My_Global_Services,1.3,902.60,0.030968,17.460,6444.0,8450.8,9.7280
73,Dell,Precision 3650,Communication / Marketing,1.3,750.80,0.021884,16.280,5322.0,7004.4,9.4140
74,Fujitsu,Celcius M740,My_Global_Services,1.3,902.60,0.030968,17.460,6444.0,8450.8,9.7280

In [28]:
# Calcul du score moyen par département
dept_scores = pd.read_sql_query("""
    SELECT Departement, AVG(Score_Final) AS Score_Moyen
    FROM impacts_calcules
    GROUP BY Departement
    ORDER BY Score_Moyen DESC
""", conn)
print("Score moyen par département :")
dept_scores

Score moyen par département :

                 Departement  Score_Moyen
0  Communication / Marketing         3.12
1         My_Global_Services         3.04
2         Information System         2.98
3         My_Rail_Subsidiary         2.94